# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cleanerupper}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Trpcic"]
  s.date = %q{2010-04-09}
  s.email = %q{mike@fluidmedia.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "./cleanerupper-0.1.0.gem",
     "./cleanerupper.gemspec",
     "./dictionary.yml",
     "./init.rb",
     "./install.rb",
     "./lib/cleanerupper.rb",
     "./pkg/cleanerupper-0.0.0.gem",
     "./rails/init.rb",
     "./tasks/cleanerupper_tasks.rake",
     "./test/cleanerupper_test.rb",
     "./test/database.yml",
     "./test/debug.log",
     "./test/schema.rb",
     "./test/test_helper.rb",
     "./uninstall.rb"
  ]
  s.homepage = %q{http://github.com/fmiopensource/cleanerupper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple database sanitation}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

